### ISSUE TITLE
You can't add more boxes

### ISSUE THREAD

**Issue by XeroOl** [thejoshwolfe/snakefall#15]
Currently, the editor doesn't let you put in more boxes

**Comment by XeroOl** [comment]
at least on the version on ur site

**Comment by thejoshwolfe** [comment]
Thanks for the feedback. This issue means the interface isn't intuitive enough, which is my fault. You can actually add blocks just fine when the screen is not focused on any one block. You get to that state when you first click the "Block" button (or press B), or by hitting Escape when editing a specific block.

I'll change it so that cycling through the existing blocks also visits "none of them" to allow you to add a new block like with the old interface.

**Comment by thejoshwolfe** [comment]
Let me know if that doesn't solve your problem.
