### ISSUE TITLE
Add decoration background tiles.

### ISSUE THREAD

**Issue by XeroOl** [thejoshwolfe/snakefall#17]
If you look at the snakebird game, they have some tiles that are colored, but you can move through them. For example, the dirt and bushes in level 21 of the game can be passed through but still are shown

**Comment by XeroOl** [comment]
I might want to make a branch and try adding the dirt myself.

**Comment by XeroOl** [comment]
i made all of the tilesets by modifying ur code: http://imgur.com/a/MuPzD

**Comment by thejoshwolfe** [comment]
Wow! Those look really good.

So this brings up a concern I have about infringing on the original game. My motivation for starting this project was to make a level editor. I originally looked into creating levels that could be played in the real game. It was only after giving up on their convoluted level format that I decided to make a clone of the whole game. It's never been my intention to take away from Snakebird's success. I don't want to undermine their work by providing a free alternative, and yet here it is: an open-source rip off of a commercial game. It's easy for lawyers to argue that I'm infringing on Snakebird's copyright, so I want to stay on the Snakebird team's good side. I don't want to come off as a competitor.

So I had two strategies to avoid having a conflict with the creators of Snakebird. 1) focus on what my project did differently, which was the level editor. That's where I've been pouring most of my focus. 2) under emphasize graphics to incentivize people to buy the original game. I plan to make a video showing off my level editor, and I want to say something like "go buy the original game to get much better graphics". I want Snakebird to have something that this project does not.

Your changes look great; don't get me wrong. But I'm starting to worry about what the Snakebird team will think. Maybe the way to resolve this is just to ask them. Idk.

Your changes would introduce a setting in the editor to choose a tileset. That would be the first thing about the level format that would be strictly aesthetic, which is undeniable evidence that this project is trying to look good. Everything else about the aesthetics could be spun as being functional: the dirt color is now different from the html page background; the new snake highlight is better at getting your attention; animated movement would better show how teleporters work; etc. But a snow-themed tileset is really just for show. I wouldn't be able to argue that that falls into my original strategy.

**Comment by XeroOl** [comment]
what about [these](http://i.imgur.com/A99hZKB.png) colored boxes? They can render exits / portals through them :D

**Comment by thejoshwolfe** [comment]
The colored boxes look good. The colors should help distinguish different boxes from one another, so that should be fine.

How to help this project is a difficult question to answer. Basically, a good answer would include a complete solution to one of the open issues on github. So I'm not really sure how to answer that question.

One thing I've noticed about [your fork](https://github.com/XeroOl/snakefall) is that you haven't merged upstream changes in a while. In fact, you seem to have pasted in the changes without telling git about it, which makes history difficult to follow and merging very painful. Consider how much duplication there is between these two commits: https://github.com/XeroOl/snakefall/commit/978c7514d658eea5c45a57bde3365b4acf82a1e2 https://github.com/thejoshwolfe/snakefall/commit/f42979630d254afd5af17bdae9cb9b3ebb1dc621 but the git history thinks those are completely separate ideas. Ideally, the color -> id variable rename should only be in one commit in both our histories.

I'm not sure I'm explaining myself very well.

**Comment by XeroOl** [comment]
yeah ik i'm probably going to abandon my fork and start a new fork.

**Comment by XeroOl** [comment]
another aesthetical suggestion: fix the box connectors to make them more intuitive. look at [these two blocks](http://wolfesoftware.com/snakefall/#level=3tFRIoTU&17&31?*z0*z0*z0*z0*n04*z0*D03*20*O1*z0*R0/b0?384&320&260&324/b1?327&331&267&391/s4?380&379&378&377/) and note how the box wiring might be un-intuitive

**Comment by thejoshwolfe** [comment]
that seems like an idea worth discussing inmore detail. moved to #19

**Comment by XeroOl** [comment]
what if you called them marker blocks instead of decorational blocks? Imagine if I wanted to mark [the path the block needs to follow in my Spike Maze level](http://wolfesoftware.com/snakefall/#level=3tFRIoTU&17&25?*70111*I0141*I0101000*01*B01010001001*B01011001031*00*8100*0100111*K010011000202*2021102020*010002*B010001102010001*5010012011010001*101*5010110020002001000201210200011*901*30201102021002*5022010011*902*402110001221*002111*00*412*0122*3122*21/b3?351&363/s1?386&385&384&383/s0?391&392&393&394/)
