### ISSUE TITLE
Performance issues with large blocks

### ISSUE THREAD

**Issue by XeroOl** [thejoshwolfe/snakefall#25]
I just went back to my level [Coral Block](http://wolfesoftware.com/snakefall/#level=3tFRIoTU&17&31?*X01*z0*z0*A04*z0*l03*Z02*z0*j02*z0*30/b0?6&68&36&67&65&128&161&224&254&190&189&221&252&253&316&346&313&344&345&315&379&348&317&287&320&289&227&228&196&102&101&39&40&71&72&135&167&199&168&136&104&73&133&164&195&258&288&318&285&223&193&162&130&129&97&66&5&4&3&2&1&32&31&62&93&94&124&155&156&187&218&217&249&250&280&311&310&341&372&373&404&435&434&466&499&500&438&406&405&437&471&472&473&474&475&506&507&508&509&478&479&448&419&389&360&391&390&420&450&449&355&325&203&263&262&232&201&202&234&265&296&297&327&326&356&386&417&416&513&512&515&516&485&486&487&518&519&520&521&522&492&523&524&525&494&463&464&433&402&371&370&338&400&430&490&459&456&457&458&428&429&399&369&340&309&278&247&216&185&154&123&122&91&29&30&28&27&90&120&89&88&87&56&25&24&54&23&22&21&207&236&205&206&176&145&210&240&209&242&336&366&335&303&334&395&394&364&333&305&274&243&245&244&211&179&148&149&116&147&146&114&113&143&142&112&83&52&51&50&19&18&79&109&78&48&17&16&15&45&107&76&75&14&13&12&11/s8?443&442&441/s7?412&411&410&409/) and the game seems to delay before moving the snakes. Also, the animation of the snakes is sometimes skipped. It most likely has to do with the giant map-sized block. This issue wasn't present when I made the level.

**Comment by thejoshwolfe** [comment]
I suspect it's the infinite loop detection code I added in #10 that's causing the problem. I have a number of ideas to work around this, such as disabling the infinite loop detection if there aren't portals directly above one another.

That being said, this level is a bit esoteric in its use of a block to form walls instead of using walls to form walls. The performance regression is my fault, and I'll look into fixing this, but it might be worth mentioning that this usecase isn't really something that's super necessary to support.

**Comment by thejoshwolfe** [comment]
I'm actually having trouble seeing any performance problem on my machine. It might be due to the type of graphics card I have or something. I'm not sure.

I've uploaded two experimental versions to try to isolate what's causing the performance problems. Please tell me how these two branches look to you:

[perf1](http://wolfesoftware.com/snakefall/experimental/perf1/#level=HyRr4JK1&17&31?*X01*z0*z0*A04*z0*z0*M02*z0*j02*z0*30/b0?6&68&36&67&65&128&161&224&254&190&189&221&252&253&316&346&313&344&345&315&379&348&317&287&320&289&227&228&196&102&101&39&40&71&72&135&167&199&168&136&104&73&133&164&195&258&288&318&285&223&193&162&130&129&97&66&5&4&3&2&1&32&31&62&93&94&124&155&156&187&218&217&249&250&280&311&310&341&372&373&404&435&434&466&499&500&438&406&405&437&471&472&473&474&475&506&507&508&509&478&479&448&419&389&360&391&390&420&450&449&355&325&203&263&262&232&201&202&234&265&296&297&327&326&356&386&417&416&513&512&515&516&485&486&487&518&519&520&521&522&492&523&524&525&494&463&464&433&402&371&370&338&400&430&490&459&456&457&458&428&429&399&369&340&309&278&247&216&185&154&123&122&91&29&30&28&27&90&120&89&88&87&56&25&24&54&23&22&21&207&236&205&206&176&145&210&240&209&242&336&366&335&303&334&395&394&364&333&305&274&243&245&244&211&179&148&149&116&147&146&114&113&143&142&112&83&52&51&50&19&18&79&109&78&48&17&16&15&45&107&76&75&14&13&12&11/s8?443&442&441/s7?412&411&410&409/f0?299/)

[perf2](http://wolfesoftware.com/snakefall/experimental/perf2/#level=HyRr4JK1&17&31?*X01*z0*z0*A04*z0*z0*M02*z0*j02*z0*30/b0?6&68&36&67&65&128&161&224&254&190&189&221&252&253&316&346&313&344&345&315&379&348&317&287&320&289&227&228&196&102&101&39&40&71&72&135&167&199&168&136&104&73&133&164&195&258&288&318&285&223&193&162&130&129&97&66&5&4&3&2&1&32&31&62&93&94&124&155&156&187&218&217&249&250&280&311&310&341&372&373&404&435&434&466&499&500&438&406&405&437&471&472&473&474&475&506&507&508&509&478&479&448&419&389&360&391&390&420&450&449&355&325&203&263&262&232&201&202&234&265&296&297&327&326&356&386&417&416&513&512&515&516&485&486&487&518&519&520&521&522&492&523&524&525&494&463&464&433&402&371&370&338&400&430&490&459&456&457&458&428&429&399&369&340&309&278&247&216&185&154&123&122&91&29&30&28&27&90&120&89&88&87&56&25&24&54&23&22&21&207&236&205&206&176&145&210&240&209&242&336&366&335&303&334&395&394&364&333&305&274&243&245&244&211&179&148&149&116&147&146&114&113&143&142&112&83&52&51&50&19&18&79&109&78&48&17&16&15&45&107&76&75&14&13&12&11/s8?443&442&441/s7?412&411&410&409/f0?299/)

**Comment by XeroOl** [comment]
I would think that the infinite loop detector only would be active if portals are present/used. Is there any disadvantage to only enabling the loop detector while a portal is in use?

**Comment by XeroOl** [comment]
perf1 appears to have little/no effect.
perf2 seems to get rid of the problem completely for me, with the exception of the support beams.
I'm guessing that the support beam cover is what's causing the problem. If that's the case, it might be possible to fix this bug when implementing #19.

**Comment by thejoshwolfe** [comment]
Alright, please try this branch:

[perf3](http://wolfesoftware.com/snakefall/experimental/perf3/#level=HyRr4JK1&17&31?*X01*z0*z0*A04*z0*z0*M02*z0*j02*z0*30/b0?6&68&36&67&65&128&161&224&254&190&189&221&252&253&316&346&313&344&345&315&379&348&317&287&320&289&227&228&196&102&101&39&40&71&72&135&167&199&168&136&104&73&133&164&195&258&288&318&285&223&193&162&130&129&97&66&5&4&3&2&1&32&31&62&93&94&124&155&156&187&218&217&249&250&280&311&310&341&372&373&404&435&434&466&499&500&438&406&405&437&471&472&473&474&475&506&507&508&509&478&479&448&419&389&360&391&390&420&450&449&355&325&203&263&262&232&201&202&234&265&296&297&327&326&356&386&417&416&513&512&515&516&485&486&487&518&519&520&521&522&492&523&524&525&494&463&464&433&402&371&370&338&400&430&490&459&456&457&458&428&429&399&369&340&309&278&247&216&185&154&123&122&91&29&30&28&27&90&120&89&88&87&56&25&24&54&23&22&21&207&236&205&206&176&145&210&240&209&242&336&366&335&303&334&395&394&364&333&305&274&243&245&244&211&179&148&149&116&147&146&114&113&143&142&112&83&52&51&50&19&18&79&109&78&48&17&16&15&45&107&76&75&14&13&12&11/s8?443&442&441/s7?412&411&410&409/f0?299/)

**Comment by XeroOl** [comment]
perf3 works perfectly.

**Comment by thejoshwolfe** [comment]
thanks for your help
