### ISSUE TITLE
When too many fruits are present, the undo function doesn't work properly

### ISSUE THREAD

**Issue by XeroOl** [thejoshwolfe/snakefall#26]
In the level that I made called Fruit Maze 2, After eating lots of fruits and hitting undo, the snake moves back without replacing the fruit.
Note that this doesn't happen on levels that were made earlier (ex: Etch-a-sketch)

**Comment by thejoshwolfe** [comment]
I've determined that there are too many fruits with the same id number. This is a problem, because objects of any type are supposed to be uniquely identified by their id number.

Some bug in the level editor allowed you to create multiple fruits with conflicting id numbers. And now this bug is immortalized in your level data. You can fix your level data by painstakingly renumbering the fruits (like `f0`) so that they're all unique. However, the real bug is in the level editor. Once that is fixed, you could just recreate your level, and the problem would be gone.

I haven't figured out what the bug is yet that's in the level editor.

**Comment by andrewrk** [comment]
> I haven't figured out what the bug is yet that's in the level editor.

I haven't actually looked at the code, but could perhaps the bug be in the level data serializer/deserializer?

**Comment by thejoshwolfe** [comment]
Figured it out. Steps to reproduce: create two fruits, `f0`, and `f1`. Delete `f0`. Create two more fruits. They're both called `f0`.

The problem was that I forgot to sort the fruits by id when looking for an unused id number.

**Comment by thejoshwolfe** [comment]
@XeroOl, I'll fix your level and update the wiki.
