### ISSUE TITLE
Plagiarized levels

### ISSUE THREAD

**Issue by JoeltheFox** [thejoshwolfe/snakefall#58]
Unfortunately a recent contributor has plagiarized levels from the original Snakebird. "fruit is too far 1" is a copy of Snakebird level 27, and also "fruit is too far 2" is quite similar to Snakebird level 19.  I think we should remove everything but will leave it to josh to judge

**Comment by thejoshwolfe** [comment]
I'm cool with plagiarizing the entire game as long as there are ads to go buy the original from Noumenon Games (which has always been there). At this point, the game is about 5 years old, so i'm not worried about the impact on Noumenon's revenue.

I would advise that levels that are direct or near copies of Noumenon's levels be separated into their own table and probably isolated onto their own wiki page, and the author credit should be Noumenon Games rather than whoever transcribed the level into this Snakefall format.

**Comment by eff96** [comment]
I said I’m not good at making levels, that’s why my levels are just regular snakebird levels with extra steps.

But yes, I think it’s more interesting to make levels that are similar to the original game where the difference is extra steps, sorry if that’s not allowed.
